[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#1A0E0A"
secondaryBackgroundColor = "#261A14"
textColor = "#F5F0EB"
font = "sans serif"
